# Generated by Django 5.1.4 on 2025-01-14 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('restaurant_review', '0003_alter_restaurantreview_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created_comment', models.DateTimeField(auto_now_add=True)),
                ('date_modified_comment', models.DateTimeField(auto_now=True)),
                ('restaurant_review',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_review',
                                   to='restaurant_review.restaurantreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
