# Generated by Django 5.1.4 on 2025-01-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0002_initial'),
        ('restaurant_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='restaurants', to='restaurant_category.category'),
        ),
    ]
