# Generated by Django 5.1.4 on 2025-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0006_alter_restaurant_city_alter_restaurant_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
