# Generated by Django 5.1.4 on 2025-01-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0007_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
    ]
